[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Smart enter"

[[mgr.prepend_keymap]]
on   = "C"
run  = "shell 'cat \"$1\" | wl-copy' --confirm"
desc = "Copy file contents to clipboard"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = "<C-1>"
run  = "plugin toggle-pane max-current"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "<C-2>"
run  = "plugin toggle-pane max-preview"
desc = "Show or hide the preview pane"
