---@diagnostic disable: undefined-global
-- Env:
hl.env("EDITOR", "nvim")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_IM_MODULE", "fcitx")
hl.env("SDL_IM_MODULE", "fcitx")
hl.env("XMODIFIERS", "@im=fcitx")
hl.env("XDG_SCREENSHOTS_DIR", "$HOME/Pictures/")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("PUB_HOSTED_URL", "https://pub.myket.ir")
hl.env("FLUTTER_STORAGE_BASE_URL", "https://pub.myket.ir")
hl.env("ANDROID_HOME", "$HOME/Android/Sdk")
hl.env("SKIKO_RENDER_API", "SOFTWARE")
hl.env("GTK_THEME", "Adwaita:dark")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("YAZI_CWD_FILE", "$HOME/.yazi-cwd")
hl.env("PATH", "$PATH:$HOME/dev/flutter/bin:$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/cmdline-tools/20.0/bin")
hl.env("FZF_DEFAULT_COMMAND", "rg --files --hidden")
